-- ============================================================================
-- OBSOLETO — NO EJECUTAR. Ver supabase/panel_clientes_paso7_seguridad.sql
--
-- Este archivo definía las policies de RLS originales del proyecto, todas
-- "to authenticated using (true)" (cualquier cuenta autenticada veía TODO,
-- sin allowlist). Quedaron superadas el 2026-08-08 por
-- panel_clientes_paso7_seguridad.sql, que las reemplaza por
-- "to authenticated using (is_usuario_autorizado())".
--
-- Se vació de SQL ejecutable a propósito (pentest 2026-08-09): si alguien
-- copia y corre este archivo completo pensando que es el script base de
-- siempre, con las policies originales habría revertido silenciosamente la
-- protección de la allowlist sin que nadie lo note hasta que fuera tarde.
--
-- Fuente de verdad actual de RLS: supabase/panel_clientes_paso7_seguridad.sql
-- ============================================================================
