import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-admin";

const NOMBRE_EMPRESA = "FUNDACIÓN UNBOUND ECUADOR";

const CATALOGO = [
  {
    nombre_puesto: "Presidenta y Representante Legal",
    area: "Nacional — Unidad Coordinadora, sucursales y subproyectos",
    supervisado_por: "Asamblea General de Miembros",
    supervisa_a: "Personal técnico, administrativo y operativo de la Unidad Coordinadora y sucursales",
    orden: 1,
    actividades: [
      "Ejercer la representación legal, judicial y extrajudicial de la Fundación en todos los actos públicos, privados y ante los entes de control",
      "Suscribir convenios, contratos y compromisos interinstitucionales orientados a la consecución de los fines y objetivos de la Fundación",
      "Planificar, convocar, presidir y ejecutar las Asambleas Ordinarias y Extraordinarias de la Junta Directiva, el equipo regional, los miembros y los socios",
      "Revisar, validar y firmar de manera conjunta con la Secretaría las convocatorias, actas, correspondencia y demás documentación oficial de las sesiones institucionales",
      "Tramitar y actualizar ante el Ministerio competente los cambios en la conformación de las Juntas Directivas y el registro de socios vigentes",
      "Elaborar el informe anual de actividades y presentar la rendición de cuentas integral ante la Junta Directiva y la Asamblea General de Miembros",
      "Elaborar los objetivos estratégicos anuales de la Fundación",
      "Liderar la construcción del Plan Operativo Anual (POA) general, con revisiones minuciosas por subproyectos y áreas",
      "Coordinar y supervisar la ejecución de los POA a nivel nacional y por cada sucursal o filial",
      "Monitorear el cumplimiento, los plazos y los fondos asignados a los \"Agentes de Cambio\", así como las metas del Semáforo de Orientación de Objetivos, dotando al equipo de los recursos necesarios",
      "Monitorear el cumplimiento de las metas del área de correspondencia y de las estrategias amigables con las familias apadrinadas",
      "Planificar, coordinar y verificar el cierre formal del programa de apadrinamiento en las familias, sucursales o comunidades que completen su ciclo o lo requieran",
      "Revisar y aprobar la distribución del presupuesto mensual y el presupuesto anual institucional, garantizando su alineación con los objetivos estratégicos y el POA",
      "Revisar y aprobar las solicitudes de ejecución presupuestaria de todos los fondos manejados por la Fundación",
      "Administrar, supervisar y controlar las cuentas bancarias institucionales y el movimiento económico, en conjunto con el Contador General",
      "Autorizar las transferencias bancarias para la liquidación de obligaciones con proveedores, pago de roles, viáticos y reembolsos justificados",
      "Revisar y aprobar las transferencias económicas directas a las cuentas de las familias apadrinadas y de los jóvenes becados",
      "Validar, mediante auditorías por muestreo en territorio, que las familias apadrinadas reciban efectivamente el beneficio económico correspondiente",
      "Liderar los procesos de reclutamiento, contratación formal y evaluación periódica del desempeño del personal",
      "Planificar, organizar y desarrollar la inducción institucional del personal de nuevo ingreso",
      "Gestionar integralmente al equipo: control de procesos internos y autorización de vacaciones, permisos, licencias y jornadas laborales",
      "Capacitar continuamente al equipo en materia legal, políticas internas y elaboración de los convenios de apadrinamiento con las familias beneficiarias",
      "Planificar y ejecutar el Programa Anual de Seguridad y Salud en el Trabajo (SST) en beneficio de los colaboradores",
      "Supervisar la compra de bienes y la contratación de servicios requeridos por la Unidad Coordinadora o los subproyectos, según el monto",
      "Revisar, verificar y validar los procesos internos de los Comités de Compras, y emitir la aprobación final de las solicitudes de compra y contratación",
      "Cotizar los servicios profesionales externos requeridos (consultorías o asistencias especializadas), según las necesidades institucionales",
      "Desarrollar e implementar el registro actualizado de control de activos fijos de la Fundación, en corresponsabilidad solidaria del inventario con el Contador General",
      "Gestionar la búsqueda y contratación de bienes inmuebles para oficinas y subproyectos a nivel nacional",
      "Planificar y organizar técnicamente las brigadas en territorio para el ingreso a nuevas comunidades y la inscripción de personas en situación de vulnerabilidad",
      "Revisar y fiscalizar el proceso formal de inscripción e inducción de las familias que ingresan al programa de apadrinamiento",
      "Controlar y verificar el cumplimiento de la meta del número de familias inscritas en el programa",
      "Supervisar la selección e inducción de los jóvenes becados y aprobar la ejecución del presupuesto del área de becas",
      "Coordinar y estructurar el plan de capacitaciones y la agenda mensual general del proyecto",
      "Revisar y aprobar el cumplimiento puntual de las obligaciones tributarias (SRI), patronales (IESS) y municipales en cada localidad y cantón donde la Fundación mantenga operaciones",
    ],
  },
  {
    nombre_puesto: "Responsable de Programas Sociales",
    area: "Unidad Coordinadora",
    supervisado_por: "Representante Legal",
    supervisa_a: "Coordinadores de Subproyecto",
    orden: 2,
    actividades: [
      "Crear formatos y controles que faciliten la operatividad de las actividades",
      "Desarrollar estrategias operativas para el cumplimiento de los objetivos del programa",
      "Dar a conocer el programa de apadrinamiento mediante los lineamientos establecidos (becas, apadrinamiento de niños, jóvenes y adultos mayores, agentes de cambio, proyectos productivos o de autosustento y gestión de practicantes), transmitiendo con claridad la misión, los valores, el liderazgo y el propósito de Unbound",
      "Velar por el buen funcionamiento del proyecto en todos los campos de desarrollo social, conforme a las 9 características y los objetivos del programa, promoviendo el trabajo en equipo y en red con todas las áreas de Unbound",
      "Implementar, controlar y manejar de forma sistemática la información de los programas, en corresponsabilidad con el Representante Legal y los coordinadores de subproyectos",
      "Garantizar el seguimiento y la escucha activa a los beneficiarios mediante técnicas y acciones creativas",
      "Actuar como agente oficial de protección del menor y del adulto mayor, diseñando y aplicando el manual de políticas internas de protección",
      "Apoyar las actividades de los AT, garantizando el cumplimiento del código de conducta y de los objetivos establecidos en el conjunto de manuales de Sede Unbound",
      "Gestionar alianzas estratégicas de servicios para las familias apadrinadas, los becados y el equipo",
      "Elaborar el plan operativo anual y la planificación mensual, con su respectivo informe",
      "Elaborar reportes, actas e informes de gestión del área social",
      "Asistir al Representante Legal en la preparación y presentación de información clara, precisa y confiable de los procesos y actividades del área social",
      "Establecer comunicación efectiva con el Representante Legal y la Unidad Coordinadora para dar trámite oportuno a los procesos con las familias apadrinadas y el equipo",
      "Realizar giras de trabajo para verificar, monitorear y evaluar la implementación de los procesos en el campo",
      "Contribuir a la mejora continua de los procesos y al mejoramiento de la Fundación",
      "Apoyar en eventualidades o contingencias del proyecto, según requerimientos del Representante Legal",
      "Realizar otras actividades afines al cargo",
    ],
  },
  {
    nombre_puesto: "Evaluador de Programas",
    area: "Comunidades y oficinas a nivel nacional",
    supervisado_por: "Representante Legal",
    supervisa_a: "Ninguno",
    orden: 3,
    actividades: [
      "Elaborar su planificación y agenda mensual, con el respectivo presupuesto de trabajo, y enviarla al Representante Legal para su aprobación",
      "Identificar el programa o los componentes del programa a evaluar",
      "Seleccionar la metodología de evaluación, ajustándola a las necesidades de información del programa",
      "Definir y diseñar la estrategia operativa de evaluación con base en las Características del Programa, incluyendo su planificación, monitoreo y seguimiento",
      "Crear formatos, controles e instrumentos que permitan una implementación clara, transparente y documentada del programa y sus políticas",
      "Establecer los parámetros y estándares básicos para la medición e implementación de la evaluación del programa",
      "Diseñar y aplicar dos procesos de evaluación de programas al año, de carácter profesional, sistemático y concluyente, que reflejen el impacto del programa en las comunidades (apadrinados, familias y becados) y aporten a la toma de decisiones sobre mejora, continuación o fortalecimiento del apadrinamiento",
      "Evaluar la selección y la participación de los apadrinados en el programa de apadrinamiento",
      "Evaluar, mediante muestreo, la inversión del beneficio entregado a las familias, orientada a la meta y el sueño del apadrinado",
      "Evaluar, definir, medir y documentar los resultados, utilizándolos para la mejora continua del programa",
      "Evaluar si los apadrinados en edad escolar cursan su instrucción educativa, de oficio o profesión, y presentar las recomendaciones correctivas para cada subproyecto",
      "Apoyar en la planificación, ejecución y evaluación de los viajes de padrinos",
      "Visitar como mínimo dos subproyectos al mes (o más, según se requiera), con visitas de tres a cuatro días según la distancia y la necesidad",
      "Realizar giras de trabajo para verificar, monitorear y evaluar la implementación de los procesos en los subproyectos",
      "Dar seguimiento a los planes operativos relacionados con los programas en los subproyectos",
      "Apoyar las estructuras operativas que permitan el abordaje y el alcance de resultados de los programas en los subproyectos",
      "Implementar los instrumentos de recolección de información del programa",
      "Administrar la base de datos de resultados del programa como insumo de retroalimentación para la toma de decisiones",
      "Elaborar los informes parciales y totales de los resultados del programa",
      "Elaborar los informes de las visitas a cada subproyecto y enviarlos al Representante Legal, con copia al subproyecto visitado",
      "Coordinar con el Representante Legal las estrategias del proyecto y los procesos de planeación anual y estratégica",
      "Validar los procesos de evaluación con el/la especialista de evaluación de programas de Sede Unbound",
      "Facilitar la información requerida al especialista de evaluación de Sede Unbound, brindar retroalimentación y recopilar información para evaluaciones globales o del AT",
      "Participar activamente en la red de evaluación de Sede Unbound y en las reuniones del equipo nacional, de las comunidades y de los subproyectos",
      "Planificar, coordinar y dar seguimiento a los talleres formativos y recreativos del equipo de becados, junto con la Encargada de Becas",
      "Promover un plan de capacitación en función de los resultados obtenidos en las evaluaciones",
      "Las demás funciones afines que, por la naturaleza del cargo, se le asignen",
    ],
  },
  {
    nombre_puesto: "Especialista de Correspondencia Nacional",
    area: "Unidad Coordinadora / Sede Nacional",
    supervisado_por: "Representante Legal",
    supervisa_a: "Asistente de Correspondencia (supervisión técnico-funcional)",
    orden: 4,
    actividades: [
      "Planificar, coordinar y organizar las actividades de cumplimiento de la correspondencia del proyecto, con alcance mensual, semestral y anual",
      "Gestionar los correos nacionales e internacionales: revisar las respuestas y enviarlas a la Sede Unbound, canalizar los requerimientos a los subproyectos y supervisar las respuestas (informes, solicitudes de información, páginas de salida y notas rápidas)",
      "Gestionar oportunamente las páginas de salida",
      "Revisar y validar las cartas y los archivos de video cargados por el personal de los subproyectos en el portal, asegurando el cumplimiento de los estándares de calidad y las pautas de protección de datos antes de su aprobación final",
      "Controlar y asegurar el cumplimiento de los tiempos de entrega de las 2 cartas regulares obligatorias al año por cada persona apadrinada del proyecto",
      "Coordinar y supervisar el ciclo fotográfico de cada subproyecto: el envío mediante enlaces y la toma de las fotografías anuales de los apadrinados y de las fichas disponibles, con el uso del material adecuado",
      "Administrar y revisar el portal y el módulo de traducciones, verificando que todas las cartas subidas a revisión sean liberadas",
      "Revisar y traducir las fichas sociales",
      "Realizar seguimiento semanal a los traductores del proyecto y efectuar el pago mensual según el número de traducciones realizadas",
      "Elaborar la solicitud de envío de dinero previamente planificado en la contestación a la nota rápida, construyendo el calendario de desembolso junto con el equipo del subproyecto",
      "Dirigir y participar en las brigadas de inscripción de nuevos interesados en el programa de apadrinamiento",
      "Realizar visitas a las comunidades y a las familias en proceso de inscripción",
      "Promover el programa de Unbound mediante reuniones y presentaciones de socialización ante escuelas, instituciones educativas y presidentes barriales, para la apertura de nuevas zonas",
      "Elaborar, revisar y validar técnicamente el manual y el material didáctico e instructivo anual que utilizan los subproyectos en el área de correspondencia",
      "Capacitar, en procesos de inducción o retroalimentación, al equipo de especialistas de correspondencia de los subproyectos",
      "Realizar visitas de acompañamiento técnico a los subproyectos para auditar la correcta ejecución de los talleres y supervisar el uso adecuado del material metodológico asignado al área",
      "Brindar acompañamiento técnico, supervisión y mentoría continua a la Asistente de Correspondencia, asegurando la correcta ejecución de los procesos de revisión, traducción y control de calidad de las cartas de todo el proyecto",
    ],
  },
  {
    nombre_puesto: "Contador General",
    area: "Unidad Coordinadora / Contabilidad",
    supervisado_por: "Representante Legal",
    supervisa_a: "Contadora Tesorera y Auxiliar Contable",
    orden: 5,
    actividades: [
      "Recibir y registrar las donaciones mensuales provenientes de Sede Unbound en el sistema Abila",
      "Distribuir el fondo de apadrinamiento conforme a la planificación institucional",
      "Registrar en Abila los débitos bancarios mensuales (internet, telefonía convencional y planes telefónicos) y los pagos a proveedores",
      "Registrar en Abila las facturas de gastos operativos de los subproyectos (suministros de limpieza, insumos médicos, talleres, entre otros)",
      "Registrar en Abila las compras de activos fijos, su depreciación, y conciliar el módulo de activos contra el balance de comprobación",
      "Revisar en el portal correspondiente y registrar la provisión del Fondo 51 en Abila",
      "Controlar, revisar y registrar en Abila las becas de los subproyectos y de la Unidad Coordinadora (Fondo 30)",
      "Mantener actualizados en Abila los módulos de códigos de proveedores, empleados y becados",
      "Colocar los asientos contables de gastos en Abila, con su respectivo soporte",
      "Postear la información en Abila previa verificación con el check list contable",
      "Elaborar y presentar las declaraciones tributarias mediante los formularios 101, 103 y 104",
      "Validar la información en Marylink y emitir el ATS mensual con sus respectivas declaraciones, asegurando la concordancia con Abila",
      "Revisar la plataforma del SRI y mantener al día el cumplimiento tributario del proyecto",
      "Controlar los pagos a instituciones públicas (SRI, IESS, municipios y demás) conforme a los plazos establecidos",
      "Elaborar las declaraciones, anexos y estados financieros anuales requeridos por las entidades de control, inspección y vigilancia",
      "Elaborar el rol de pagos general, incluyendo fondos de reserva, préstamos y liquidaciones del personal",
      "Gestionar en el IESS los avisos de entrada, salida y novedades del personal",
      "Mantener al día las plataformas del SUT del MDT y del IESS: actas de finiquito, registro de contratos, actualización de datos, décimos tercero y cuarto",
      "Elaborar el reporte para el pago de décimos a los empleados y registrarlo en Marylink y Abila",
      "Registrar en Abila el asiento contable (JV) de la provisión del rol general",
      "Elaborar la planilla general para la transferencia mensual de los apadrinados del proyecto",
      "Elaborar y enviar a Sede Unbound los reportes financieros mensuales: amarre de ingresos mensual y acumulado, distribución de fondos apadrinados, balance de comprobación, balance general, estado de resultados, comparativo presupuesto vs. gasto (KPI), conciliaciones bancarias y de caja chica, cierre del mes, proyecto NTB-SOA Analytics y consolidación",
      "Elaborar reportes y cuadres de las cuentas asignadas (caja chica y cuentas 20401, 20402, 20404, 20405, 13100, 13300 y 14110 — balance de comprobación), asegurando la concordancia entre Marylink y Abila",
      "Aplicar el check list para contadores y coordinadores en cada cierre mensual",
      "Elaborar conjuntamente con el equipo de trabajo el presupuesto anual del proyecto",
      "Presentar los reportes financieros en la asamblea de socios o junta directiva",
      "Elaborar y revisar la toma física de activos fijos para inventarios",
      "Guiar y monitorear el registro contable de la Contadora Tesorera y el Auxiliar Contable",
      "Capacitar y retroalimentar periódicamente al equipo del área contable",
      "Apoyar las ausencias temporales de la Contadora Tesorera y el Auxiliar Contable",
      "Revisar y firmar la información contable mensual del proyecto Ecuador",
      "Elaborar las políticas contables y financieras alineadas con el Manual Financiero de Sede Unbound y las NIIF",
      "Asistir a las reuniones convocadas por la Fundación",
      "Apoyar las visitas a familias cuando se requiera",
    ],
  },
  {
    nombre_puesto: "Contadora Tesorera",
    area: "Unidad Coordinadora / Contabilidad — Tesorería",
    supervisado_por: "Contador General",
    supervisa_a: "Ninguno",
    orden: 6,
    actividades: [
      "Ejecutar las transferencias bancarias para el pago a proveedores, empleados, becarios y apadrinados, conforme a la programación de pagos",
      "Controlar los saldos de las cuentas bancarias del proyecto",
      "Gestionar la actualización de cuentas bancarias para las transferencias",
      "Ejecutar los pagos a instituciones públicas (SRI, IESS, municipios y demás) acorde a las necesidades requeridas",
      "Descargar y enviar los estados de cuenta bancarios al Contador General",
      "Apoyar la elaboración de la planilla general para la transferencia mensual de los apadrinados del proyecto",
      "Elaborar las conciliaciones bancarias mensuales del proyecto",
      "Administrar la caja chica asignada y elaborar el cuadre mensual para su conciliación en Abila",
      "Elaborar reportes y cuadres de las cuentas asignadas de caja chica, asegurando la concordancia entre Marylink y Abila",
      "Verificar los respaldos y comprobantes de las transacciones de tesorería",
      "Registrar en Abila las transacciones de débitos bancarios y los pagos del proyecto",
      "Registrar en Abila las facturas y comprobantes de gastos operativos asignados al área de tesorería",
      "Validar la información ingresada en Marylink y su concordancia con el sistema Abila",
      "Colocar los asientos contables de los gastos correspondientes a tesorería en Abila",
      "Mantener actualizado el módulo de proveedores en el sistema contable",
      "Apoyar la revisión de la plataforma del SRI y la validación de la información tributaria",
      "Apoyar la emisión del ATS mensual desde Marylink y su conciliación con Abila",
      "Apoyar el manejo de las plataformas del IESS y del SUT del MDT en lo relacionado con tesorería",
      "Apoyar el registro del rol de pagos y el pago de décimos a los empleados en Marylink y Abila",
      "Apoyar la elaboración de los reportes financieros mensuales para Sede Unbound",
      "Apoyar la elaboración del presupuesto anual junto al equipo del área contable",
      "Apoyar la toma física de activos fijos para inventarios",
      "Apoyar las ausencias temporales del Contador General y del Auxiliar Contable",
      "Apoyar las visitas a familias cuando se requiera",
      "Asistir a las reuniones convocadas por la Fundación",
    ],
  },
  {
    nombre_puesto: "Auxiliar Contable",
    area: "Unidad Coordinadora / Contabilidad",
    supervisado_por: "Contador General",
    supervisa_a: "Ninguno",
    orden: 7,
    actividades: [
      "Revisar y registrar en Marylink y Abila las facturas de gastos de los subproyectos (suministros de limpieza, insumos médicos, talleres, entre otros)",
      "Elaborar los comprobantes de diario y las retenciones",
      "Revisar y registrar mensualmente en Marylink y Abila las transacciones de débitos bancarios de proveedores de servicios (internet, telefonía convencional y planes telefónicos)",
      "Registrar contablemente la compra de activos en Marylink y Abila",
      "Revisar y registrar en Marylink y Abila las facturas de traductores",
      "Revisar en el portal y registrar en Marylink y Abila el Fondo 51",
      "Controlar, revisar y registrar las becas de los subproyectos y la Unidad Coordinadora (Fondo 30) en Marylink y Abila",
      "Pagar los bonos a apadrinados sin cuenta bancaria con cargo a los fondos especiales (51 y 53) en Marylink y Abila",
      "Revisar y registrar las cajas chicas de los subproyectos y la Unidad Coordinadora con sus comprobantes de liquidación de compras y comprobantes contables en Marylink y Abila",
      "Revisar, registrar y cerrar los adelantos y depósitos de empleados para visitas a apadrinados o traslados de local, con sus respectivos comprobantes de liquidación y contables en Marylink y Abila",
      "Alimentar el Anexo Transaccional Simplificado (ATS) para su declaración",
      "Mantener actualizados en Excel los códigos de becados (SPE), proveedores (VE) y empleados (EGU)",
      "Realizar las compras de suministros de oficina y aseo para la Unidad Coordinadora",
      "Controlar los pagos a instituciones públicas (SRI, IESS, municipios) según las necesidades requeridas",
      "Recibir la valija de las distintas oficinas y archivar los documentos originales",
      "Organizar, clasificar y resguardar toda la documentación física y digital de soporte que respalda las transacciones procesadas",
      "Archivar el rodaje del vehículo, las guías y las liquidaciones de haberes",
      "Realizar el análisis técnico, revisión y depuración mensual de las cuentas contables seleccionadas",
      "Colaborar periódicamente en el levantamiento, etiquetado y constatación física de los activos fijos de la Fundación, asegurando que los registros contables coincidan con la existencia real de los bienes",
      "Participar, junto con el equipo de trabajo, en la elaboración del presupuesto anual",
      "Las demás funciones afines al cargo que disponga el jefe inmediato",
    ],
  },
  {
    nombre_puesto: "Coordinador de Subproyecto",
    area: "Subproyecto y Comunidades / Coordinación Territorial",
    supervisado_por: "Responsable de Programas de la Fundación",
    supervisa_a: "Especialista y Promotora del subproyecto (si aplica en la sucursal); becarios-voluntarios",
    orden: 8,
    actividades: [
      "Elaborar convenios de apadrinamiento con beneficiarios nuevos del programa de apadrinamiento",
      "Aplicación de autoevaluaciones del semáforo de orientación de objetivos",
      "Organizar los objetivos del Plan Operativo Anual (POA) y diseñar la agenda mensual de actividades",
      "Planificar y desarrollar talleres formativos, recreativos y lúdicos para familias apadrinadas, jóvenes becados y adultos mayores",
      "Fomentar espacios de capacitación para representantes y líderes comunitarios, preparando los materiales didácticos necesarios",
      "Dirigir reuniones periódicas con el equipo de trabajo y guiar las actividades de aprendizaje de los jóvenes becados",
      "Realizar visitas domiciliarias y seguimiento directo a familias en situaciones críticas para la entrega de ayudas especiales",
      "Realizar el seguimiento académico de los apadrinados y constatar el buen uso de los beneficios otorgados por la fundación",
      "Llenar la ficha social, verificar la información de las familias y organizar los expedientes (boletines, información para la entrega de beneficios, actualización de datos personales, certificados y convenios de apadrinamiento)",
      "Mantener canales de comunicación abiertos (presencial, telefónico o WhatsApp) para informar, acompañar, capacitar sobre políticas y responder dudas de las familias",
      "Elaborar el presupuesto mensual y gestionar las solicitudes de fondos específicos (Fondos 10 y 15, fondos de intención de padrino y fondos de talleres)",
      "Organizar la documentación contable, gestionar el pago de servicios básicos y mantener el control de los activos fijos del subproyecto",
      "Coordinar la compra y entrega de beneficios personalizados cuando se requieran, controlar saldos y gestionar la actualización de cuentas bancarias para transferencias",
      "Seleccionar proveedores para las compras del subproyecto menores a mil dólares y, en montos mayores, guiar al comité de compras de padres de familia para una adquisición transparente",
      "Preparar reuniones mensuales con líderes comunitarios y gestionar el trabajo conjunto con otras instituciones locales cuando se requiera",
      "Elaborar y enviar informes periódicos de actividades, visitas a familias y ejecución de fondos especiales al responsable de área",
      "Las demás actividades afines al cargo",
    ],
  },
  {
    nombre_puesto: "Especialista de Correspondencia",
    area: "Subproyecto PCM y comunidades",
    supervisado_por: "Coordinador del Subproyecto o sucursal / Especialista de Correspondencia Nacional",
    supervisa_a: "Ninguno",
    orden: 9,
    actividades: [
      "Revisar la correspondencia y su traducción para el envío digital a los apadrinados",
      "Editar las fotografías y verificar que cumplan los requerimientos del manual de correspondencia",
      "Colaborar en la grabación de videomensajes en las comunidades de familias con dificultades tecnológicas",
      "Participar en la elaboración del material para cada proceso anual y mensual",
      "Revisar diariamente todos los procesos de correspondencia y las actualizaciones del portal",
      "Capacitar a los apadrinados y sus familias en el cumplimiento de la carta de presentación, los mensajes regulares (carta o video), las cartas de contestación, las finales y la fotografía anual",
      "Desarrollar talleres, capacitaciones y programas en las comunidades apadrinadas",
      "Contactar mensualmente a las nuevas familias apadrinadas para el taller de inducción",
      "Alimentar la base de datos interna de cumplimiento de la correspondencia de los apadrinados",
      "Elaborar las fichas sociales conjuntamente con el Coordinador del Subproyecto",
      "Actualizar las fichas y los datos en el portal por visitas o cambios de información de la familia",
      "Elaborar los listados de actividades conforme a las actualizaciones mensuales",
      "Evaluar los procesos de retiro junto con el Coordinador del Subproyecto, documentarlos y gestionar el retiro en el portal",
      "Realizar visitas a familias por acompañamiento, inscripciones, solicitudes de información, visita anual u otras circunstancias",
      "Participar en la elaboración del plan operativo anual",
      "Elaborar su planificación mensual y el informe mensual de actividades",
      "Participar en las reuniones, capacitaciones y talleres presenciales y virtuales convocados por Unbound",
      "Formar parte de los programas y planes de mejora de seguridad y salud en el trabajo",
      "Utilizar diariamente el correo institucional, Teams y demás plataformas requeridas para comunicarse con el equipo",
      "Realizar otras actividades afines al cargo",
      "Realizar la adquisición de suministros de oficina",
      "Gestionar el archivo con toda la información de cada apadrinado",
    ],
  },
  {
    nombre_puesto: "Especialista de Subproyecto",
    area: "Subproyecto (oficina y comunidades)",
    supervisado_por: "Coordinador de Subproyecto / Responsable de Programas Sociales",
    supervisa_a: "Ninguno",
    orden: 10,
    actividades: [
      "Mantener activa la comunicación del apadrinado con su patrocinador mediante el cumplimiento de su carta, foto y, de requerirse, solicitudes de información",
      "Dar contestación ágil a las solicitudes de información y notas rápidas de cada mes",
      "Capacitar a las familias en la elaboración de correspondencia y la toma de fotografías",
      "Elaborar material y guiar a las familias y apadrinados en la elaboración de cartas",
      "Visitar a las familias apadrinadas (presencial o virtual) y a las familias candidatas al apadrinamiento",
      "Entregar las e-cartas a las familias con su respectiva traducción",
      "Gestionar el cumplimiento del envío de la fotografía anual",
      "Elaborar las fichas sociales junto con el equipo de la Unidad Coordinadora",
      "Actualizar las fichas y los datos en el portal",
      "Conservar un archivo individual de cada apadrinado y mantener en orden los archivos de la oficina del subproyecto",
      "Adquirir los suministros de oficina",
      "Administrar, registrar y reportar los gastos de caja chica",
      "Elaborar reportes, informes y actualizaciones de información de los apadrinados del subproyecto",
      "Asistir al Coordinador del Subproyecto en la preparación y presentación de información clara, precisa y confiable",
      "Establecer comunicación efectiva con el Representante Legal y el equipo del proyecto para dar trámite oportuno a los procesos",
      "Elaborar el plan operativo anual y la planificación mensual",
      "Utilizar diariamente el correo institucional, Teams y demás plataformas para comunicarse con el equipo",
      "Participar en las reuniones, capacitaciones y talleres presenciales o virtuales convocados por Unbound",
      "Contribuir a la mejora continua de los procesos",
      "Realizar otras actividades afines al cargo",
    ],
  },
  {
    nombre_puesto: "Asistente de Correspondencia",
    area: "Unidad Coordinadora",
    supervisado_por: "Especialista de Correspondencia Nacional / Representante Legal",
    supervisa_a: "Ninguno",
    orden: 11,
    actividades: [
      "Traducir las cartas de agradecimiento que los subproyectos cargan mensualmente, las cartas urgentes (presentación, despedida, graduación) y aquellas con escaneo o escritura poco legible",
      "Traducir las fichas de reemplazo o crecimiento requeridas por el proyecto",
      "Revisar las traducciones para agilizar el proceso de entrega",
      "Editar las fotografías al formato establecido (480×640) y verificar que cumplan los requerimientos del manual de correspondencia",
      "Aprobar las fotografías y alimentar la base de datos interna de fotografías pendientes",
      "Notificar a los subproyectos el incumplimiento de las fechas establecidas para el registro de fotografías",
      "Acompañar a los subproyectos en los talleres anuales de fotografía",
      "Revisar las cartas cargadas al portal y verificar el tiempo de registro para evitar retiros por incumplimiento",
      "Notificar a los subproyectos el incumplimiento de fechas según el cronograma",
      "Alimentar la base de datos interna con las fechas de registro de cada carta",
      "Llevar la base de tiempos de cada subproyecto para el envío y la respuesta de @cartas",
      "Notificar a los subproyectos las @cartas no enviadas y las no contestadas",
      "Elaborar e imprimir los listados de nuevos beneficiados, retirados y @cartas recibidas",
      "Elaborar reportes operativos del área de correspondencia para el Representante Legal y la Especialista Nacional",
      "Acompañar los talleres organizados por los subproyectos",
      "Dar seguimiento a los especialistas de subproyecto en el cumplimiento de tiempos y actividades",
      "Realizar visitas a familias para acompañamiento, inscripciones, solicitudes de información u otras circunstancias",
      "Apoyar en eventualidades o contingencias del proyecto, según requerimientos del Representante Legal",
      "Elaborar el plan operativo anual y la planificación mensual del cargo",
      "Utilizar diariamente el correo institucional, Teams y demás plataformas para comunicarse con el equipo",
      "Establecer comunicación efectiva con la Unidad Coordinadora y el equipo del proyecto para dar trámite oportuno a los procesos con las familias apadrinadas",
      "Participar en las reuniones, capacitaciones y talleres presenciales o virtuales convocados por Unbound",
      "Participar en los programas y planes de mejora de seguridad y salud en el trabajo",
      "Realizar otras actividades afines al cargo",
    ],
  },
  {
    nombre_puesto: "Promotora Social",
    area: "Subproyecto (oficina y comunidades)",
    supervisado_por: "Coordinador de Subproyecto",
    supervisa_a: "Ninguno",
    orden: 12,
    actividades: [
      "Apoyar la vinculación y comunicación entre el apadrinado y su padrino mediante el seguimiento de cartas y fotografías",
      "Realizar visitas domiciliarias a familias apadrinadas y candidatas para acompañamiento e inscripción",
      "Apoyar en la capacitación a familias en los procesos de correspondencia y en la elaboración de material didáctico",
      "Colaborar en talleres formativos, recreativos y lúdicos organizados por el subproyecto",
      "Apoyar en la actualización de fichas sociales y datos en el portal del subproyecto",
      "Apoyar en la administración de suministros y en el control de caja chica bajo supervisión del Coordinador",
      "Elaborar informes y reportes de actividades requeridos por el Coordinador del Subproyecto",
      "Participar en reuniones, capacitaciones y planes de seguridad y salud en el trabajo convocados por Unbound",
    ],
  },
];

export async function POST(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.SEED_SECRET}`) {
    return NextResponse.json({ error: "No autorizado" }, { status: 401 });
  }

  const { data: empresa, error: empError } = await supabaseAdmin
    .from("empresas_mdt")
    .select("id")
    .ilike("nombre", `%UNBOUND%`)
    .maybeSingle();

  if (empError || !empresa) {
    return NextResponse.json({ error: "Empresa UNBOUND no encontrada en empresas_mdt" }, { status: 404 });
  }

  // Eliminar catálogo previo si existe
  await supabaseAdmin.from("catalogo_puestos").delete().eq("empresa_id", empresa.id);

  const rows = CATALOGO.map((p) => ({
    empresa_id: empresa.id,
    nombre_puesto: p.nombre_puesto,
    area: p.area,
    supervisado_por: p.supervisado_por,
    supervisa_a: p.supervisa_a,
    actividades: p.actividades,
    orden: p.orden,
  }));

  const { error: insertError } = await supabaseAdmin.from("catalogo_puestos").insert(rows);

  if (insertError) {
    return NextResponse.json({ error: insertError.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, empresa: NOMBRE_EMPRESA, puestos: rows.length });
}
